import express , {type Express} from 'express';
import GetData from './module/getData';
const app:Express = express();

export interface IvenderProductList {
    "No.": string;
    "PO Date": string;
    "PO Number": string;
    "PO GENERATED BY": string;
    "VN Code": string;
    "Vendor Name": string;
    "Product": string;
    "Project name ": string;
    "Drwg. No": string;
    "Total Qty": string;
    "Price Per Nos": string;
}
export interface IVendorAggregatedDetail {
    "No.": string;
    "PO Date": string;
    "PO Number": string;
    "PO GENERATED BY": string;
    "VN Code": string;
    "Vendor Name": string;
    "Product": string[]; // Aggregated as array
    "Project name ": string;
    "Drwg. No": string;
    "Total Qty": string;
    "Price Per Nos": string[]; // Aggregated as array
}
export interface IvenderDetailList{
   [venderName: string]: IVendorAggregatedDetail
}

app.get('/',async(_req:express.Request,res:express.Response)=>{
    const FILE_PATH = 'credentials.json'; // Replace with your actual key file path
    const SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly'];
    const SPREADSHEETID = '195kPYe6mVoWXJw27SKEn4SO7L5d32bXCSJlfDzuvPpc'; // Replace with your actual spreadsheet ID
    const RANGE = '25-26!A1:K528'; // Replace with your actual range
    const SPREADSHEETID1 = '1K6yyMuAJMCr6x_lYk8ya-CWarIomrYh1rW0_P8XBnx8'
    const RANGE1 = '2425!A1:K1013';
    const SPREADSHEETID2 = '11MvVNbsSvBMkS6uAb_iSyCxq707seTY9dOqdsUunn-E'
    const RANGE2 = '23-24!A1:K710';
    const data = new GetData(SPREADSHEETID, RANGE, SCOPES, FILE_PATH);
    const result = await data.getData();
    const data1 = new GetData(SPREADSHEETID1, RANGE1, SCOPES, FILE_PATH);
    const result1 = await data1.getData();
    const data2 = new GetData(SPREADSHEETID2, RANGE2, SCOPES, FILE_PATH);
    const result2 = await data2.getData();
    const allResult:IvenderProductList[] = [...result, ...result1, ...result2]
    let allResultObj = {} as IvenderDetailList;
    let modifiedResult:IVendorAggregatedDetail[] = []
    for (const item of allResult) {
        const vendorName = item['Vendor Name'] as keyof IvenderDetailList ?? "" as string;
        if(item && item['Vendor Name'] in allResultObj) {
            if(!allResultObj[vendorName].Product.includes(item.Product) && !allResultObj[vendorName]['Price Per Nos'].includes(item['Price Per Nos'])){
                allResultObj[vendorName].Product.push(item.Product.concat(`- ${item['Price Per Nos']} Rs - ${item['PO Date']}`));
                
            }
         }
     else {
        allResultObj[vendorName] = JSON.parse(JSON.stringify(item));
        allResultObj[vendorName].Product = [item.Product];
    }   
    }
    modifiedResult = Object.values(allResultObj);
    modifiedResult.sort((a,b)=>Number(a['VN Code']) - Number(b['VN Code']));
    res.json(modifiedResult);
})

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
}); 
