import express , {type Express} from 'express';
import GetData from './module/getData';
const app:Express = express();

export interface IvenderProductList {
    "No.": string;
    "PO Date": string;
    "PO Number": string;
    "PO GENERATED BY": string;
    "VN Code": string;
    "Vendor Name": string;
    "Product": string;
    "Project name ": string;
    "Drwg. No": string;
    "Total Qty": string;
    "Price Per Nos": string;
}
export interface IvenderDetailList{
   [x: string]: any
}

app.get('/',async(_req:express.Request,res:express.Response)=>{
    const FILE_PATH = 'credentials.json'; // Replace with your actual key file path
    const SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly'];
    const SPREADSHEETID = '195kPYe6mVoWXJw27SKEn4SO7L5d32bXCSJlfDzuvPpc'; // Replace with your actual spreadsheet ID
    const RANGE = '25-26!A1:K528'; // Replace with your actual range
    const SPREADSHEETID1 = '1K6yyMuAJMCr6x_lYk8ya-CWarIomrYh1rW0_P8XBnx8'
    const RANGE1 = '2425!A1:K1013';
    const data = new GetData(SPREADSHEETID, RANGE, SCOPES, FILE_PATH);
    const result = await data.getData();
    const data1 = new GetData(SPREADSHEETID1, RANGE1, SCOPES, FILE_PATH);
    const result1 = await data1.getData();
    const allResult:IvenderProductList[] = [...result, ...result1];
    let allResultObj = {} as IvenderDetailList;
    let modifiedResult:IvenderDetailList[] = []
    for (const item of allResult) {
        const vendorName = item['Vendor Name'] as keyof IvenderDetailList ?? "" as string;
        if(item && item['Vendor Name'] in allResultObj) {
        if(!allResultObj[vendorName].Product.includes(item.Product)){
            allResultObj[vendorName].Product.push(item.Product);
            
        }
        if(!allResultObj[vendorName].Product.includes(item['Price Per Nos'])){
            allResultObj[vendorName]["Price Per Nos"].push(item['Price Per Nos']);}

     }else {
        allResultObj[vendorName] = JSON.parse(JSON.stringify(item));
        allResultObj[vendorName].Product = [item.Product];
        allResultObj[vendorName]["Price Per Nos"] = [item['Price Per Nos']];
     }   
    }
    modifiedResult.push(allResultObj);
    modifiedResult.sort((a: any, b: any) => {
        const keyA = Object.keys(a)[0];
        const keyB = Object.keys(b)[0];
        const vnCodeA = a[keyA]["VN Code"] || "";
        const vnCodeB = b[keyB]["VN Code"] || "";
        return vnCodeA - vnCodeB;
    })
    res.json(modifiedResult);
})

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
}); 
